### ISSUE TITLE
Missing Headers

### ISSUE THREAD

**Issue by FigoHunter** [Meowuu7/QuasiSim#3]
I have some problems configuring DiffHand when I install setup.py in DiffHand/core. It seems that header files are missing for multiple external libraries and projects.

**Comment by Meowuu7** [comment]
Hi @FigoHunter ,

Thanks for raising the issue. Some headers were not tracked by `.git` initially, but I've added them now. I've tested it by re-cloning the repo, creating a new virtual environment, and setting up DiffHand. So everything will be ok if you try it again. 

Please let me know if you encounter any other problems. Thank you!

**Comment by FigoHunter** [comment]
@Meowuu7 It works all good. Thank you!
